-- 本项目默认使用 SQLite，不需要手动创建数据库或输入密码。
-- 后端首次启动会自动生成 backend/data_task.db 和全部 ORM 表。
--
-- 该文件仅保留给明确选择 PostgreSQL 的部署场景；请在 PostgreSQL 管理工具中
-- 按实际账号权限执行下面的语句，不要把密码写入脚本或提交到仓库：
-- CREATE DATABASE data_task_platform;
